### PR TITLE
general: prepare for release on PyPI

### LINKED ISSUE #79: Make first release
After applying useful goodies from inveniosoftware/cookiecutter-invenio-module, we need to push to pypi beard-0.1.0 so that we have a stable version to start working on.

### PR DESCRIPTION
**Pull request by jacquerie**
Closes #79.

### CODE REVIEW

**Comment by MSusik** [comment]
:+1:

**Comment by jacquerie** [comment]
Ah, right : ) https://travis-ci.org/inspirehep/beard/jobs/124478805#L563

**Comment by jacquerie** [comment]
@MSusik, care for a review? I will take care of submitting it to PyPI.

**Comment by kaplun** [comment]
To me looks good! Was just wandering. When you install beard, the `examples` directory doesn't get installed. I wonder how the `author-disambiguation` app is currently used then within `invenio-beard`

**Comment by glouppe** [comment]
The philosophy was that beard is a library, not an application. Examples are examples of what can be done with the library, but they are not part of it.

**Comment by MSusik** [comment]
@jacquerie Looks good

**Comment by jacenkow** [comment]
@kaplun `invenio-beard` and `beard-server` do not rely on 'examples'.

**Comment by kaplun** [comment]
OK. @jacquerie :shipit:

**Comment by kaplun** [comment]
Can you actually write in commit log that it closes #79 :)

**Comment by jacquerie** [comment]
You can actually do it from a PR as well! https://github.com/blog/1506-closing-issues-via-pull-requests

On the other hand the presence of the dot in the end might be a problem. So I'll modify the commit to be safe : )

**Comment by kaplun** [comment]
Figo!

**Comment by glouppe** [comment]
Thanks for the last touches @jacquerie !

Shall we make a 0.2 release and ship that to PyPI?

**Comment by kaplun** [comment]
Why not directly this very version? :smiley:

**Comment by jacquerie** [comment]
Err... Did I do something wrong? https://pypi.python.org/pypi/beard appears to work, `pip install beard` appears to work, am I missing something?

**Comment by jacquerie** [comment]
Oh, I see! You actually already tagged a 0.1, which doesn't match what I pushed as 0.1 on PyPI.

**Comment by jacquerie** [comment]
What I did: removed the 0.1 from PyPI, pushed a convenience commit to be tagged for 0.2, pushed that to PyPI. Now all should be (finally!) correct.

**Pull request merged**
